"""Agents own inboxes; tools do work. Both are registered, never inferred from task names."""
from __future__ import annotations

from collections.abc import Callable
import asyncio
import json
import os
from pathlib import Path
import subprocess
from typing import Literal

from jsonschema import Draft202012Validator
from pydantic import BaseModel, ConfigDict, Field, model_validator

from verda.legacy import digest
from verda.runtime import AgentModel


class AgentDefinition(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    key: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,63}$")
    label: str
    description: str
    prompt: str
    version: str = "1"
    model: AgentModel = Field(default_factory=AgentModel)
    tools: tuple[str, ...] = ()
    delegates: tuple[str, ...] = ()
    max_turns: int = Field(default=16, ge=1, le=100)


class ToolDefinition(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    key: str = Field(pattern=r"^[a-z][a-z0-9_.-]{0,127}$")
    label: str
    description: str
    transport: Literal["python", "script", "mcp", "unconnected"] = "unconnected"
    effect: Literal["read", "write"] = "read"
    resource: str | None = None
    min_interval_seconds: int = Field(default=0, ge=0, le=86400)
    input_schema: dict = Field(default_factory=lambda: {"type": "object"})
    # Resolved from trusted local configuration, never generated by the model.
    command: tuple[str, ...] = ()
    server_url: str | None = None
    remote_name: str | None = None
    timeout_seconds: int = Field(default=30, ge=1, le=120)


class AgencyConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    agents: tuple[AgentDefinition, ...]
    tools: tuple[ToolDefinition, ...]

    @model_validator(mode="after")
    def references(self):
        agents = {a.key for a in self.agents}
        tools = {t.key for t in self.tools}
        if len(agents) != len(self.agents) or len(tools) != len(self.tools):
            raise ValueError("Duplicate agent or tool")
        for a in self.agents:
            if set(a.tools) - tools or set(a.delegates) - agents:
                raise ValueError("Unknown tool or delegation target")
        for t in self.tools:
            Draft202012Validator.check_schema(t.input_schema)
            if t.effect == "write" and not t.resource:
                raise ValueError("Write tools need a serialized resource")
            if t.transport == "script" and not t.command:
                raise ValueError("Script tool needs an explicit command")
            if t.transport == "mcp" and (not t.remote_name or not (t.server_url or t.command)):
                raise ValueError("MCP tool needs an explicit server and tool name")
        return self

    @property
    def revision(self):
        return digest(self.model_dump(mode="json"))

    @classmethod
    def load(cls, path: Path | None = None):
        return cls.model_validate_json((path or Path(__file__).with_name("default.json")).read_text())


class ResourceBlocked(RuntimeError):
    """An adapter reports CAPTCHA, rate limiting or session loss. Stop the resource."""


class TransientToolError(RuntimeError):
    """Adapter explicitly reports a retryable read failure; writes stay uncertain."""
    def __init__(self, code='source_unavailable', retry_after_seconds=0):
        super().__init__(code)
        if not isinstance(retry_after_seconds,(int,float)) or not 0 <= retry_after_seconds <= 86400:
            raise ValueError('Invalid retry delay')
        self.retry_after_seconds=retry_after_seconds


class Registry:
    def __init__(self, config: AgencyConfig, handlers: dict[str, Callable] | None = None):
        self.config = config
        self.agents = {a.key: a for a in config.agents}
        self.tools = {t.key: t for t in config.tools}
        self.handlers = dict(handlers or {})
        if set(self.handlers) - self.tools.keys():
            raise ValueError("Handler without tool definition")

    def available(self, key):
        tool = self.tools[key]
        return key in self.handlers or tool.transport in {"script", "mcp"}

    def validate(self, agent, key, arguments):
        if key not in self.agents[agent].tools:
            raise ValueError("tool_not_granted")
        Draft202012Validator(self.tools[key].input_schema).validate(arguments)

    def call(self, key, arguments):
        tool = self.tools[key]
        if key in self.handlers:
            result = self.handlers[key](arguments)
        elif tool.transport == "script":
            # Fixed argv, no shell, JSON over stdin. Scripts remain trusted local code.
            result = self._script(tool, arguments)
        elif tool.transport == "mcp":
            result = asyncio.run(self._mcp(tool, arguments))
        else:
            raise RuntimeError("tool_not_connected")
        encoded = json.dumps(result, ensure_ascii=False, allow_nan=False)
        if len(encoded.encode()) > 32768:
            raise ValueError("tool_output_too_large")
        return json.loads(encoded)

    @staticmethod
    def _script(tool, arguments):
        import tempfile
        import signal
        with tempfile.TemporaryFile() as output, tempfile.TemporaryFile() as errors:
            process = subprocess.Popen(tool.command, stdin=subprocess.PIPE, stdout=output, stderr=errors,
                                       env={k: v for k, v in os.environ.items() if k in {"PATH", "HOME", "TMPDIR"}},
                                       start_new_session=True)
            try:
                process.communicate(json.dumps(arguments).encode(), timeout=tool.timeout_seconds)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                process.wait()
                raise RuntimeError("script_timeout") from None
            if process.returncode:
                raise RuntimeError("script_failed")
            output.seek(0)
            data = output.read(32769)
            if len(data) > 32768:
                raise ValueError("tool_output_too_large")
            return json.loads(data)

    @staticmethod
    async def _mcp(tool, arguments):
        from mcp import Client
        from mcp.client.stdio import StdioServerParameters
        target = tool.server_url or StdioServerParameters(command=tool.command[0], args=list(tool.command[1:]), env={})
        async with asyncio.timeout(tool.timeout_seconds):
            async with Client(target) as client:
                # No automatic import of the server's other tools or instructions.
                result = await client.call_tool(tool.remote_name, arguments)
                if result.is_error:
                    raise RuntimeError("mcp_tool_failed")
                return result.structured_content if result.structured_content is not None else {
                    "content": [b.model_dump(mode="json") for b in result.content]}
