let catalog, selected='manager', tab='capabilities';
const labels={model:'Model',connector:'Kaynak adaptörü',deterministic:'Normal kod'};
const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
function render(){
  const list=$('agent-list');list.replaceChildren();
  catalog.agents.forEach((a,i)=>{const b=node('button',undefined,'agent-button'+(selected===a.key?' active':''));b.setAttribute('aria-pressed',selected===a.key);b.append(node('span',String(i+1).padStart(2,'0'),'agent-icon'));const title=node('span');title.append(node('strong',a.label),node('small',a.title));b.append(title);b.onclick=()=>{selected=a.key;tab='capabilities';render()};list.append(b)});
  const a=catalog.agents.find(a=>a.key===selected), detail=$('agent-detail');detail.replaceChildren();
  const head=node('div',undefined,'detail-head'),heading=node('div');heading.append(node('p','UZMAN DOSYASI','eyebrow'),node('h2',a.label));head.append(heading,node('span',a.key==='manager'?'Öneri bağlantısı hazır':a.key==='assessment'?'Kural motoru hazır':'Canlı bağlantı bekliyor','badge '+(['manager','assessment'].includes(a.key)?'ready':'pending')));detail.append(head,node('p',a.description,'description'));
  const model=node('div',undefined,'model-row');[['Model sağlayıcısı',a.model.provider==='codex'?'Codex':a.model.provider],['Model',a.model.model||'Codex varsayılanı'],['Çağrı üst süresi',a.model.timeout_seconds+' saniye']].forEach(([k,v])=>{const f=node('div');f.append(node('small',k),node('strong',v));model.append(f)});detail.append(model);
  const tabs=node('div',undefined,'tabs');tabs.setAttribute('role','tablist');[['capabilities','Yetkinlikler ve sınırlar'],['prompt','Yönerge / prompt'],['execution','İşlem türleri']].forEach(([id,label])=>{const b=node('button',label,'tab'+(tab===id?' selected':''));b.setAttribute('role','tab');b.setAttribute('aria-selected',tab===id);b.onclick=()=>{tab=id;render()};tabs.append(b)});detail.append(tabs);
  if(tab==='prompt'){detail.append(node('p',a.prompt_status==='active_preview'?'Bu metin, çalışan yönetici önerisi çağrısının kullandığı yönergedir. v1 · Salt okunur':'Taslak yönerge · Henüz canlı bir agent’a bağlı değil. Bu metin şu anda modele gönderilmiyor.','prompt-note'),node('pre',a.prompt,'prompt'));}
  else if(tab==='capabilities'){const grid=node('div',undefined,'cap-grid');[['Yapabilecekleri',a.permissions,''],['Yapamayacakları',a.restrictions,'restrict']].forEach(([title,items,cls])=>{const section=node('div',undefined,cls);section.append(node('h3',title));const ul=node('ul');items.forEach(t=>ul.append(node('li',t)));section.append(ul);grid.append(section)});detail.append(grid);if(selected==='sahibinden')detail.append(node('p','Gönderim hedefi: belirlediğin kurallar içinde otomatik, istisnalarda sana sorar. Mesaj gönderici henüz uygulanmadı.','prompt-note'));}
  if(tab!=='prompt'){const actions=node('div',undefined,'action-list');a.actions.forEach(x=>{const row=node('div',undefined,'action-row');row.append(node('span',x.label),node('span',labels[x.kind],'kind'),node('span',x.status==='ready'?'Hazır':'Planlandı','badge '+(x.status==='ready'?'ready':'pending')));actions.append(row)});detail.append(actions)}
}
fetch('/control/catalog').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{catalog=data;render();$('browser-target').textContent=data.browser.target;$('browser-note').textContent=data.browser.note;$('pacing-note').textContent=data.pacing.note;$('recovery').textContent=data.pacing.recovery;data.pacing.stop_on.forEach(t=>$('stop-on').append(node('li',t)));[[data.pacing.parallel,'aynı anda iş'],[data.pacing.interval_seconds+' sn','en az iş aralığı'],[data.pacing.batch_size+' iş','bir çalışma grubu'],[data.pacing.batch_break_minutes+' dk','gruplar arası mola']].forEach(([n,label])=>{const e=node('div',undefined,'limit');e.append(node('strong',n),node('span',label));$('limits').append(e)})}).catch(()=>{$('agent-detail').replaceChildren(node('p','Yönetim bilgileri yüklenemedi. Yerel sunucunun çalıştığını kontrol edip sayfayı yenile.','empty'))});
