const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const states={queued:'Sırada',running:'Çalışıyor',retry_wait:'Yeniden deneme bekliyor',blocked:'Bekliyor',succeeded:'Tamamlandı',failed:'Başarısız',cancelled:'İptal',complete:'Tamamlandı',pending:'Bekliyor'};
const events={run_created:'Araştırma planı oluşturuldu',task_claimed:'Uzman görevi ve girdiyi aldı',task_succeeded:'Görev tamamlandı',task_blocked:'Görev beklemeye alındı',task_failed:'Görev başarısız',task_retry_wait:'Yeniden deneme planlandı',lease_expired:'Çalışanın süreli sahipliği doldu',run_cancelled:'Araştırma iptal edildi'};
const legacyEvents={task_claimed:'Görev alındı',task_succeeded:'Görev tamamlandı',task_failed:'Görev başarısız',outbox_prepared:'Mesaj taslağı hazırlandı',outbox_state:'Mesaj durumu güncellendi',seller_task_handoff:'Satıcı iletişim görevi devredildi',item_updated:'İlan kaydı güncellendi',deterministic_check_recorded:'Kural kontrolü kaydedildi'};
let catalog, snapshot, searchTimer, listVersion=0, detailVersion=0, offset=0, currentCase=null, run=null, selectedTask=null, traceEvents=[], archiveEvents=[], archiveCursor=0;
const agentName=key=>catalog.agents.find(a=>a.key===key)?.label||key;
const actionName=key=>catalog.agents.flatMap(a=>a.actions).find(a=>a.key===key)?.label||key;
const date=value=>new Date(typeof value==='number'?value*1000:value).toLocaleString('tr-TR');
async function get(path){const r=await fetch(path);if(r.status===401){$('session-message').hidden=false;$('session-message').textContent='Özel ilan geçmişi için yerel inceleme oturumu gerekli. Sunucunun oluşturduğu tek kullanımlık yerel bağlantıyı aç. Bu ekran verilerini herkese açmaz.';throw Error('Yerel inceleme oturumu açık değil.')}if(!r.ok)throw Error('Kayıt yüklenemedi. Sunucuyu kontrol edip yeniden dene.');return r.json()}
function payload(value){return el('pre',JSON.stringify(value,null,2),'payload')}
function error(message){$('flow-panel').replaceChildren(el('div',message,'flow-empty'))}
function activeChoice(key){document.querySelectorAll('.case-choice').forEach(b=>b.classList.toggle('active',b.dataset.key===key))}
async function loadList(append=false){const v=++listVersion;try{const demos=$('source-select').value==='demos';$('case-search').hidden=demos;if(!append){offset=0;$('cases').replaceChildren()}const data=await get(demos?'/control/private/demos':'/control/private/cases?search='+encodeURIComponent($('case-search').value)+'&offset='+offset);if(v!==listVersion)return;snapshot=data.snapshot_id||null;const rows=demos?data.runs:data.cases;$('case-count').textContent=demos?rows.length+' örnek çalışma':data.total+' ilan · salt okunur arşiv';$('more-cases').hidden=demos||!data.has_more;rows.forEach(row=>{const b=el('button',undefined,'case-choice');b.dataset.key=row.id;b.append(el('strong',demos?'Örnek araştırma · '+row.id.slice(0,6):row.title||'Başlıksız ilan'),el('small',demos?'Sentetik · '+date(row.created_at):'#'+row.id+' · '+(row.lifecycle==='excluded'?'Elenmiş':'Araştırma kaydı')));b.onclick=()=>{activeChoice(row.id);if(demos){currentCase=null;loadRun(row.id)}else{currentCase={...row,snapshot};loadCase()}};$('cases').append(b)});if(!rows.length&&!append)$('cases').append(el('p',demos?'Henüz örnek çalışma yok. verda demo-run ile oluşturulabilir.':'Eşleşen ilan yok.','muted'))}catch(e){error(e.message)}}
async function loadCase(append=false){const v=++detailVersion,c=currentCase;if(!c)return;try{const data=await get('/control/private/cases/'+encodeURIComponent(c.snapshot)+'/'+encodeURIComponent(c.id)+'?after_id='+(append?archiveCursor:0));if(v!==detailVersion)return;run=null;archiveEvents=append?[...archiveEvents,...data.legacy_events]:data.legacy_events;archiveCursor=data.next_after_id;const panel=$('flow-panel');panel.replaceChildren();const box=el('div',undefined,'flow-box');box.append(el('p','GERÇEK İLAN · YEREL ARŞİV','eyebrow'),el('h2',data.title||'#'+data.id),el('p','#'+data.id+' · Kaynak sürümü '+data.source_revision,'muted'));if(data.runs.length){const select=el('select',undefined,'run-picker');select.setAttribute('aria-label','İlanın V2 araştırması');select.append(new Option('V2 araştırma çalışması seç…',''));data.runs.forEach(r=>select.append(new Option(date(r.created_at)+' · Gölge çalışma',r.id)));select.onchange=()=>{if(select.value)loadRun(select.value)};box.append(select)}else box.append(el('div','Bu ilan için henüz V2 agent çalışması kaydedilmedi. Aşağıdaki eski olaylardan agent’lar arası veri aktarımı çıkarımı yapılmıyor. Yeni akışı görmek için soldan “Eski sabit görev örnekleri”nı seçebilirsin.','flow-banner'));panel.append(box);const history=el('div',undefined,'flow-box');history.append(el('h3','Eski araştırma geçmişi'),el('p','Kaynak olaylar korunmuştur. Agent, prompt veya aktarılan girdi kaydı olmayan alanlar bilinmiyor kabul edilir.','muted'));archiveEvents.forEach(e=>{const item=el('details',undefined,'event-row');item.append(el('summary',(legacyEvents[e.kind]||e.kind)+' · '+date(e.at)),el('p',e.kind,'muted'),el('p','Kaynak olay #'+e.id+(e.task_id?' · Görev #'+e.task_id:''),'muted'),payload(e.payload));history.append(item)});if(!archiveEvents.length)history.append(el('p','Bu ilana bağlı olay kaydı yok.','muted'));if(data.has_more){const more=el('button','Sonraki olayları yükle','refresh');more.onclick=()=>loadCase(true);history.append(more)}panel.append(history)}catch(e){if(v===detailVersion)error(e.message)}}
async function loadRun(id,append=false){const v=++detailVersion;try{const data=await get('/control/private/runs/'+encodeURIComponent(id)+(append?'?after_id='+run.next_after_event_id:''));if(v!==detailVersion)return;traceEvents=append?[...traceEvents,...data.events]:data.events;run=data;if(!data.tasks.some(t=>t.id===selectedTask))selectedTask=data.tasks.find(t=>t.state!=='succeeded')?.id||data.tasks.find(t=>t.step_key==='parcel')?.id||data.tasks[0]?.id;renderRun()}catch(e){if(v===detailVersion)error(e.message)}}
function renderRun(){const panel=$('flow-panel');panel.replaceChildren();const box=el('section',undefined,'flow-box');box.append(el('p',run.mode==='demo'?'ESKİ SABİT GÖREV PLANI · SENTETİK VERİ':'İLANA BAĞLI V2 AKIŞI · GÖLGE ÇALIŞMA','eyebrow'),el('h2',currentCase?.title||'Eski sabit görev planı'),el('p','Durum: '+(states[run.status]||run.status)+' · Girdi sürümü '+run.source_revision,'graph-status'),el('div',run.mode==='demo'?'Bu önceki sürümün sabit görev planıdır; yeni agent çatısını temsil etmez. Her kutu bir görevdir, agent değildir. İlan, parsel ve ölçüm sonuçları sentetiktir; canlı kaynak araştırması değildir.':'Bu çalışma gerçek ilana bağlıdır; canlı adaptörler henüz hazır değildir. Tamamlanmış araştırma olarak değerlendirilmez.','flow-banner'));
  const counter=el('div',undefined,'flow-counter');counter.append(el('span',run.tasks.filter(t=>t.state==='succeeded').length+'/'+run.tasks.length+' adım tamamlandı'),el('span',run.tasks.filter(t=>t.state==='blocked'||t.state==='failed').length+' engel / hata'));box.append(counter);
  const graph=el('div',undefined,'graph'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');graph.append(svg);const levels={},byKey=Object.fromEntries(run.tasks.map(t=>[t.step_key,t]));run.tasks.forEach(t=>{levels[t.step_key]=t.dependencies.length?Math.max(...t.dependencies.map(k=>levels[k]))+1:0});for(let level=0;level<=Math.max(...Object.values(levels));level++){const row=el('div',undefined,'graph-level');run.tasks.filter(t=>levels[t.step_key]===level).forEach(t=>{const b=el('button',undefined,'task-node '+t.state+(selectedTask===t.id?' active':''));b.dataset.task=t.step_key;b.setAttribute('aria-label',actionName(t.action)+' · '+(states[t.state]||t.state));b.append(el('small',agentName(t.agent)),el('strong',actionName(t.action)),el('small',states[t.state]||t.state));b.onclick=()=>{selectedTask=t.id;renderRun()};row.append(b)});graph.append(row)}box.append(graph);const legend=el('div',undefined,'legend');legend.append(el('span','Girdi aktarımı kaydedildi'),el('span','Plan bağımlılığı · aktarım kaydı yok'));box.append(legend);panel.append(box);
  const draw=()=>{svg.replaceChildren();const root=graph.getBoundingClientRect();run.tasks.forEach(t=>t.dependencies.forEach(key=>{const from=Array.from(graph.querySelectorAll('.task-node')).find(n=>n.dataset.task===key),to=Array.from(graph.querySelectorAll('.task-node')).find(n=>n.dataset.task===t.step_key);if(!from||!to)return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=a.left+a.width/2-root.left,y1=a.bottom-root.top,x2=b.left+b.width/2-root.left,y2=b.top-root.top,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} C ${x1} ${(y1+y2)/2}, ${x2} ${(y1+y2)/2}, ${x2} ${y2}`);if(Object.hasOwn(t.last_claim?.input_snapshot||{},key))path.classList.add('recorded');svg.append(path)}))};requestAnimationFrame(draw);window.onresize=draw;
  const t=run.tasks.find(t=>t.id===selectedTask);if(!t)return;const detail=el('section',undefined,'flow-box');detail.append(el('p','SEÇİLİ ADIM','eyebrow'),el('h2',agentName(t.agent)+' · '+actionName(t.action)));const meta=el('div',undefined,'trace-meta');meta.append(el('span',(states[t.state]||t.state)),el('span',t.attempts+' deneme'),el('span',t.last_claim?'Son başlama: '+date(t.last_claim.at):'Henüz başlamadı'),el('span',run.mode==='demo'?'Çalıştırıcı: sentetik worker · model çağrısı yok':'Model / prompt sürümü: kayıt yok'));detail.append(meta);if(t.reason)detail.append(el('div',t.reason==='connector_not_implemented'?'Bekleme nedeni: canlı kaynak adaptörü henüz uygulanmadı.':t.reason,'flow-banner'));if(t.waiting_on.length)detail.append(el('p','Beklediği işler: '+t.waiting_on.map(k=>actionName(byKey[k].action)).join(', '),'muted'));
  const columns=el('div',undefined,'detail-columns'),inputs=el('div'),output=el('div');inputs.append(el('h3','Kimden ne aldı?'));if(!t.dependencies.length)inputs.append(el('p','Önceki agent girdisi yok. Çalışmanın ilan referansı ve girdi sürümü başlangıç bağlamıdır.','muted'));t.dependencies.forEach(key=>{const transfer=el('div',undefined,'transfer');transfer.append(el('strong',agentName(byKey[key].agent)+' → '+agentName(t.agent)));if(Object.hasOwn(t.last_claim?.input_snapshot||{},key)){transfer.append(el('p','Görev alınırken kaydedilen girdi','muted'),payload(t.last_claim.input_snapshot[key]))}else transfer.append(el('p',t.attempts?'Bu eski çalışmada girdi aktarımı kaydedilmemiş. Önceki sonuç, gerçekten alınmış girdi gibi gösterilmez.':'Bu bir plan bağımlılığı. Adım henüz veri almadı.','muted'));inputs.append(transfer)});output.append(el('h3','Ne üretti / kime aktarılacak?'));output.append(t.result?payload(t.result):el('p','Henüz sonuç yok.','muted'));const recipients=run.tasks.filter(child=>child.dependencies.includes(t.step_key));output.append(el('p',recipients.length?'Bağlı sonraki işler: '+recipients.map(child=>agentName(child.agent)+' / '+actionName(child.action)).join(', '):'Bu adımın ardından tanımlı başka görev yok.','muted'));columns.append(inputs,output);detail.append(columns);panel.append(detail);
  const history=el('section',undefined,'flow-box');history.append(el('h3','Bu adımın olay geçmişi'));traceEvents.filter(e=>e.task_id===t.id).forEach(e=>{const row=el('details',undefined,'event-row');row.append(el('summary',events[e.kind]||e.kind),el('time',date(e.at)),payload(e.details));history.append(row)});if(run.has_more_events){const more=el('button','Daha fazla olay yükle','refresh');more.onclick=()=>loadRun(run.id,true);history.append(more)}panel.append(history);
}
$('source-select').onchange=()=>{detailVersion++;currentCase=null;run=null;$('case-search').value='';$('flow-panel').replaceChildren(el('div','Soldan bir kayıt seç.','flow-empty'));loadList()};$('case-search').oninput=()=>{clearTimeout(searchTimer);listVersion++;searchTimer=setTimeout(()=>loadList(),250)};$('more-cases').onclick=()=>{offset+=25;loadList(true)};$('refresh').onclick=()=>{if(run)loadRun(run.id);else if(currentCase)loadCase();else loadList()};
get('/control/catalog').then(data=>{catalog=data;return loadList()}).catch(e=>error(e.message));
